sudo: required

language: node_js
node_js:
  - "8"

services:
  - docker

before_install:
  - pyenv global 2.7.13

install:
  - npm install --dev
  - npm install travis-ecs-deploy -g

script:
  - yarn lint

env:
  global:
    - IMAGE_NAME=goodbotai/sofia
    - DEPLOY_BRANCHES=master
    # AWS_REGION
    - secure: "E7N7V46PolOSwsghYWmZCVGELJHgJk8faPJiycW+BSBz2u9IGm4zwDuoD4+/gVJpKcPKlo7Er1DOW3q6Jzo3sbxlKcMVfh+u4FjWz4hYMOfiie1vr1GzTkVFzU6HCTgsKKVOyTc5L3bhBRAd6sUCCCkWvo7e5BOC0UwnOhKLDy4/z+N5P++rgb9k8mQciDJDYt2YrzJWJsSgWMX3MSy8hOLrPOwFRTtYmTrlGxPtJFf7QaqwSY32nmccr9+eoEolWJVWmcaGm996j8Yf356fhyQBUh1KlgZqI3qPi9l1M5PjalY+q5c5yGB1Ofqt4wWpaW+9FY0AOnPZVtOxXrGhtQKtS3D76D8wOaQ8/TBJKSwvg8hBQse+AucD/lNGEuV1t2ubHfHQUcglpEssh6JpTVO+uw/JtewMu6j2WBiUYLw54JDxct4IMG1FqBcC8KN8qF/n5UABqJbGsiC2oBRECmOUOlaFZ/BaJvS3L4TJccWL+MXZXLTYtcQVC3+x4qF5Il3XnfnegbGRkQn3QIO1agq4VKYlcnW9sAmizgKNz1z51F8OijywzmjONNEJaZTWIT1+R1HZGUkOpwk77cpTw6r9ujCNsADAdmQXOW6Y1vWt9PuDaeDE53MgAcFnqBaktHzdjWBdYOhTSXbPAB0e8/LiMxJVBi+SAPeC57awqzk="
    # AWS_ACCESS_KEY_ID
    - secure: "Il2gjEMoo8lWN4s8Deuhs2SAy3hgPQf4pImTdqeh2extRAaw6vecAYdxe1Ex2FmO0eLQs+QkvoaRUQQUZ6GIAPH7EoRd6IwFoC0S7KFpznKXnOID+DluwajffnDJm9sPnlXthrbJXuI34jY+8qjNO2XgymhwLjnWxaHv/oAnpR2HxGGJYV4KiODqA0tQtmIYsd2YMXb+iFuKC/4+RocBP2rDqKFkPAIhgRuORfzZZg5/H0S3sGQbcF/rJsEIh3Gjqb4EC7qb2CvebfHzMCWO82OWvEOXvV97wXFo9nMKek+DBg24jovHs4dgZc4gT/qL3ufvexMcj4bhI161bmR2YRXUndFxlmSomniQE6TJT/w/AtB2QLOI6lXI7XWcXMhpiGp5M96WVpz0CwchBfKZx42UMELcCdrl4Q4w1WACrlJZK0cpgVokf9WT25n0u5b6o9AKmXwIlcz+6bGPZGDkTHUHYiywGEN5jCAWi7MvGQHcOgBxK5VxFEnfmUDijWkgXlb1WgMIrH0PwACOvJVTSmIafN9M8s4AEMAEuHCsexEomPbYPV4s1u74NxAc1aJyJG4Fm1B/SuTycw/Gk/hTL1F+SX7TCIAJ5Ex8AzODqgB7rEP1yJCEr8kOWJpy25p7KkoXXJnrgBe+kUI7QG4r5JIUG99BLbtTA1WlLARVzA4="
    # AWS_SECRET_ACCESS_KEY
    - secure: "KSpCQiOid2lKzjThyZ8zYCa4eGXAN71MQ7zXj7NLMVlRCCyL0AbePeC5VnuRcuvNWzMz4iqwIdLC7o0NFaa+l2oGZu1vBaETVj2xacQTU729QW077Max8kQmBUBnwe86MEtWspqwuFg2kqNiCZ2Ej5P1zP3sMtBFn2sIfc9otFTrb8Mv+7N9O8UWMQCUrsvE6j3aa3qD8y8eKyEr5acKj0GroRB8K7KDRNx/mYsEnkWHv77nMxHv8exHzrcAJFijiSfFRmw/r2h6Rq9NiHvU6SRxSK8TA631q8+zvTpFwE4oMkUvdUfx1R+If2YMFmT3kiTmWVkjfaVBvWIgs99Nvq0m5fvNWLolo9K2Bmq2CPVBTuroSvSk2F2mVmEbo/ou9ErgOy6Idsbpk24gaH1lh0LTfS25lESDzlqd/SQO+xJf6QV1d7bwCDfze2XG60f06Hpl6IaaCeDkK7YXxjrcrSzDIHKghnsEPAxrYOiWHtmkcjhc8PPfbwUZsnFoFqgrBCrapklTQ1XWzNEdrqrd+VXs4CZiBET7BmrrJKGTHnh7odCWFlDNHBY9ShHljx99CD9/x/oi0rzoZ3Ffz6qzQdRgHJgfu2L/JYZGqQaEps9cl2iV1mDD98ZSfbuBNGespF6uwEYb2H4ZEiXdxlPnZtd1azzuokeAMNAMJEm8Q38="
    # REMOTE_IMAGE_URL
    - secure: "iG//zYw4+02N87KNfwtfWvUnw9Sjj80KNwV47iU+8DgCFmmYtRR4oMg3vhYuo0wAiCJnGzl6GzK4DEToOQFix3AEQc2ea6Zp2dJcHbab2JMcGV9Dm3bcKliysU53HZu+VCmDHaVocX1HyemNotqPelauMIfYwCEs9G5/SXfnzLpQLBXZPtX1rAcnFvhhVinA8PRzIhwMJdEnA/cJSepO5sIXWh3/LoCbq2CpQw0sXJTkh5jRbvRe1vkN5OGmje6Bfjl2qS/txBkH8sdbQOdzO4V6dH1rCBtxffJ9r3D8hu8VO1l8/qKgsc1uni2IW4xlafN9TIqRPPVpjYCoWOdHdyAlCDqEy3FYFfIalKsDCEQwdFFNXwrTS2wTM4ZJSK/0tzsd/G8OjjaDgv8PrHWzeGT+4iDRSarevluWzaBQ1BFDgnifcaFgIkp4zfDuO1FRnU98QX/ROCcwDdQTMgNAiQq2F+RKRkTf+JRcValR08bLzbOGxB7UQjLamxIfKX/AqY3O4qzGjLVH7xPb3rvl1gnP3dwX2ZZ9SUVuCUfWY4BOd04Ka8W09dyYRbCZAyXHKunXYTHchvBjWy9JGZ/FP4HyR9QhFto5NbNdMDcCGhjx4iUYkAkkExt5nL6NgiVVwnWXqRXggAUvF2WXEMSg90e2PZWNLPTGRnJsXdledJI="

deploy:
  # deploy to staging environment
  skip_cleanup: true
  provider: script
  ECS_CLUSTER_MASTER: sofia-production
  ECS_SERVICE_MASTER: sofia-production
  script:
    - yarn run travis-ecs-deploy
  on:
    branch: master
